### ISSUE TITLE
Switch to NFS shared folders for Virtualbox

### ISSUE THREAD

**Issue by ferrarimarco** [netgroup/kubernetes-playground#135]
We switched to NFS when using the libvirt provider. Is it necessary to do the same for Virtualbox?

**Comment by StefanoSalsano** [comment]
IMO there is no strong motivation... from a functional perspective NFS and vboxsf are the same
I do not see performance issues currently, in kites we will measure networking performances only on libvirt, and we will have to make sure that file sync traffic do not interfere (it's on the management network)

**Comment by ferrarimarco** [comment]
This was more to reduce the variance in the environment, so both providers use the same method.

**Comment by StefanoSalsano** [comment]
FYI see https://peshmerge.io/how-to-speed-up-vagrant-on-windows-10-using-nfs/ 
NFS will not work when using windows as host :-(
maybe it will work when using MAC as host... so windows users will need to stick to VirtualBox shared folders
