### ISSUE TITLE
lack of permission performing the command 'vagrant package', with libvirt provider

### ISSUE THREAD

**Issue by zvfvrv** [netgroup/kubernetes-playground#184]
we encountered a lack of permissions while executing the command:

vagrant package base-box-builder.k8s-play.local --output kubernetes-playground-base.box

<pre>
$ vagrant package base-box-builder.k8s-play.local --output kubernetes-playground-base.box
Welcome to Kubernetes playground!
Vagrant provider : libvirt
Networking plugin : calico
==> base-box-builder.k8s-play.local: Packaging domain...
==> base-box-builder.k8s-play.local: Require set read access to /var/lib/libvirt/images/base-box-builder.k8s-play.local.img. sudo chmod a+r /var/lib/libvirt/images/base-box-builder.k8s-play.local.img
</pre>

Indeed 

<pre>$ ls -la /var/lib/libvirt/images/
total 32698248
drwxr-xr-x 2 root         root                4096 Apr 17 10:37 <font color="#729FCF"><b>.</b></font>
drwxr-xr-x 7 root         root                4096 Mar 29 14:23 <font color="#729FCF"><b>..</b></font>
-rw------- 1 libvirt-qemu libvirt-qemu  1566703616 Apr 17 11:31 base-box-builder.k8s-play.local.img</pre>

**Comment by simonezacca** [comment]
When I use the command:

`vagrant package base-box-builder.k8s-play.local --output kubernetes-playground-base.box`

I encountered this permissions error:

> cp: cannot open '/boot/vmlinuz-5.3.0-53-generic' for reading: Permission denied

I solved it this way:

`sudo chmod 755 /boot/vmlinuz*`

**Comment by ferrarimarco** [comment]
Note: the commands that @simonezacca reported both run on the host.

**Comment by ferrarimarco** [comment]
Leaving this open for now, will have a look if we can reproduce.

**Comment by ferrarimarco** [comment]
Not reproducible, and likely a host permission issue.
