### ISSUE TITLE
support multiple host nodes for vagrant-libvirt provider

### ISSUE THREAD

**Issue by StefanoSalsano** [netgroup/kubernetes-playground#208]
this is needed by SRv6-PM project (issue #204)

scenario: we have two hosts h1 and h2 on which we can run libvirt and kvm with nested virtualization (actually they are VMs, but we cannot influence their setup).
on each host we can run libvirtd and we would like to control them from a single vagrant instance running on h1 (or everywhere), the vagrant instance will connect to libvirt1 locally (or to the h1:libvirtd address) and to libvirt2 provider remotely (of course this should be extendable to N libvirtd!)

pre-requirements for scenario1: we install kvm and libvirt on each host, while we should install vagrant-libvirt plugin only in the host that runs vagrant (h1 or everywhere)

The [vagrant-libvirt plugin](https://github.com/vagrant-libvirt/vagrant-libvirt#provider-options) exposes quite a few interesting settings. For example we might point to different libvirtd hosts for different VMs (master-1 and worker-1 run on host-1, while worker-2 runs on host-2).

**Comment by ferrarimarco** [comment]
Hi @StefanoSalsano 

Which criteria do we want to support to assign guests to the different libvirt hosts?

This is an interesting feature, because we now dynamically generate the VMs list.

**Comment by ferrarimarco** [comment]
@StefanoSalsano is this still a required feature?

**Comment by ferrarimarco** [comment]
@StefanoSalsano ping

**Comment by StefanoSalsano** [comment]
@ferrarimarco yes this is still needed, but low priority right now...

**Comment by ferrarimarco** [comment]
Ok! Leaving this out of a specific milestone for now. We can revisit later.
